[build]
    command = "make all"
    publish = "dist"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

# [[redirects]]
    # from = "/posts/*"
    # to = ""
    # status = 200
    
[build.environment]
  HUGO_VERSION = "0.134.3"
